name: Update Server
on:
  push:
    branches: [ master ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
           hosts: 'christian@moonbutt.club'
           privateKey: ${{ secrets.PRIVATE_KEY }}
           command: cd /var/www/html && git pull
